sudo: false
language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
  - EMACS_VERSION=24.3
  - EMACS_VERSION=24.4
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25.1
  # 25.2 is identical to 25.3 except for a critical security bug in
  # enriched text mode (see Emacs Bug#28350).
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26 # emacs-26 branch, built daily
  - EMACS_VERSION=master # master branch, built daily
  allow_failures:
    - env: EMACS_VERSION=master
install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version
script:
  - $EMACS -Q --batch -f batch-byte-compile swap-regions.el
